access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  application:
    name: API-Server
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gcp:
      security:
        firebase:
          enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  resources:
    static-locations: classpath:/public/, classpath:/static/
spring-doc:
  swagger-ui:
    path=/custom-swagger-ui.html
springdoc:
  show-actuator=true
mapbox:
  access-token: ${MAPBOX_ACCESS_TOKEN}
app:
  awsServices:
    bucketName: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
management:
  endpoints:
    web:
      exposure:
        include: "*"
token:
  access:
    expiration:
      minutes: 15
  refresh:
    expiration:
      days: 30
  activation:
    expiration:
      hours: 24